[package]
name = "asset-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "asset"
path = "src/main.rs"

[dependencies]
asset-core.workspace = true
asset-infra.workspace = true
asset-plugin-api.workspace = true
asset-runtime.workspace = true

anyhow.workspace = true
clap.workspace = true
comfy-table.workspace = true
rpassword.workspace = true
tokio.workspace = true
toml.workspace = true

[dev-dependencies]
async-trait.workspace = true
