[package]
name = "asset-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
asset-core.workspace = true
asset-plugin-api.workspace = true

anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
comfy-table.workspace = true
rpassword.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
