/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 审计对象存储与资源数据库的一致性。 */
        post: operations["audit_storage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_security_audit_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/directory-grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["my_directory_grants"];
        put: operations["grant_directory"];
        post?: never;
        delete: operations["revoke_directory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_users"];
        put?: never;
        post: operations["create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_user_status"];
        trace?: never;
    };
    "/directories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出当前目录的直接子目录和资源。 */
        get: operations["list_directory"];
        put?: never;
        /** 创建一个空逻辑目录。 */
        post: operations["create_directory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查。 */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resource-kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出当前后端支持的资源类型。 */
        get: operations["list_resource_kinds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页列出资源。 */
        get: operations["list_resources"];
        put?: never;
        /** 创建纯元数据资源。 */
        post: operations["create_resource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/content/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 流式上传内容并创建资源。
         * @description 请求体必须是原始二进制流。资源名称、存储键等元信息从 query 参数读取，MIME 类型
         *     优先使用请求的 `Content-Type` header。
         */
        put: operations["upload_resource_content_stream"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按 ID 查询资源。 */
        get: operations["find_resource"];
        put?: never;
        post?: never;
        /** 软删除资源。 */
        delete: operations["soft_delete_resource"];
        options?: never;
        head?: never;
        /** 更新资源。 */
        patch: operations["update_resource"];
        trace?: never;
    };
    "/resources/{id}/actions/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 执行资源插件动作。 */
        post: operations["execute_resource_action"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取资源内容。 */
        get: operations["get_resource_content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 预览资源内容。 */
        get: operations["preview_resource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 物理移除资源和对象内容。 */
        delete: operations["remove_resource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 在线阅读资源内容。
         * @description 当前 MVP 只支持声明 `read` action 的 kind，并要求内容可转换为文本。
         */
        get: operations["read_resource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取资源缩略图。 */
        get: operations["thumbnail_resource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 扫描本地对象存储目录并补齐资源数据库。 */
        post: operations["scan_storage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 单个对象存储审计问题。 */
        AuditStorageIssueResponse: {
            /** @description 对象存储中的实际 SHA-256。 */
            actual_sha256?: string | null;
            /**
             * Format: int64
             * @description 对象存储中的实际大小。
             */
            actual_size?: number | null;
            /** @description 数据库记录的 SHA-256。 */
            expected_sha256?: string | null;
            /**
             * Format: int64
             * @description 数据库记录的大小。
             */
            expected_size?: number | null;
            /** @description 内容存储键。 */
            key: string;
            /** @description 问题类型：missing_blob、size_mismatch、checksum_mismatch、orphan_blob。 */
            kind: string;
            /** @description 关联资源 ID；孤儿对象为空。 */
            resource_id?: string | null;
        };
        /**
         * @description 审计对象存储与资源数据库一致性的请求。
         * @example {
         *       "prefix": "",
         *       "sha256": true
         *     }
         */
        AuditStorageRequest: {
            /** @description 可选对象键前缀；未提供时审计整个对象存储根命名空间。 */
            prefix?: string;
            /** @description 是否计算并对比 SHA-256。默认开启。 */
            sha256?: boolean | null;
        };
        /** @description 对象存储一致性审计响应。 */
        AuditStorageResponse: {
            /** @description 本次审计覆盖的对象存储前缀。字段名为兼容旧客户端而保留。 */
            audited_directory: string;
            /**
             * Format: int64
             * @description 检查的资源内容引用数量。
             */
            checked_resources: number;
            /** @description 审计问题明细。 */
            issues: components["schemas"]["AuditStorageIssueResponse"][];
            /**
             * Format: int64
             * @description size 或 checksum 不一致的问题数量。
             */
            mismatched: number;
            /**
             * Format: int64
             * @description 数据库引用但对象不存在的数量。
             */
            missing: number;
            /**
             * Format: int64
             * @description 对象存在但未被任何资源引用的数量。
             */
            orphaned: number;
            /**
             * Format: int64
             * @description 扫描到的普通文件数量。
             */
            scanned: number;
        };
        AuthenticatedUser: {
            id: string;
            is_admin: boolean;
            username: string;
            workspace_directory: string;
        };
        /**
         * Format: binary
         * @description OpenAPI 中表示原始二进制请求或响应体的 schema。
         */
        BinaryContent: string;
        /** @description 内容校验和响应。 */
        ChecksumResponse: {
            /** @description 校验和算法类型。 */
            kind: string;
            /** @description 校验和值。 */
            value: string;
        };
        /** @description 创建逻辑目录请求。 */
        CreateDirectoryRequest: {
            /** @description 新目录名称，只允许单个路径段。 */
            name: string;
            /** @description 父目录路径，根目录为空字符串。 */
            parent_path?: string;
        };
        /**
         * @description 创建纯元数据资源请求。
         * @example {
         *       "name": "resources_not_blob",
         *       "kind": "core:unknown",
         *       "metadata": {
         *         "summary": {
         *           "description": "A metadata-only resource",
         *           "tags": [
         *             "demo",
         *             "document"
         *           ]
         *         }
         *       }
         *     }
         */
        CreateResourceRequest: {
            /** @description 资源所在逻辑目录；根目录为空字符串。 */
            directory?: string | null;
            /** @description 可选资源类型。 */
            kind?: string | null;
            metadata?: null | components["schemas"]["ResourceMetadataRequest"];
            /** @description 资源展示名。 */
            name: string;
            /** @description 可选初始状态：`active` 或 `archived`。 */
            status?: string | null;
        };
        CreateUserRequest: {
            is_admin?: boolean;
            password: string;
            username: string;
            workspace_directory?: string | null;
        };
        Credentials: {
            password: string;
            username: string;
        };
        DirectoryGrantResponse: {
            directory: string;
            is_workspace: boolean;
            permission: string;
        };
        /** @description 目录浏览响应。 */
        DirectoryListingResponse: {
            /** @description 直接子目录。 */
            folders: components["schemas"]["ResourceDirectoryResponse"][];
            /** @description 当前目录路径。 */
            path: string;
            /** @description 当前目录下的资源分页。 */
            resources: components["schemas"]["ResourcePageResponse"];
        };
        /** @description 统一 HTTP 错误响应。 */
        ErrorResponse: {
            /** @description Stable machine-readable error code when available. */
            code?: string | null;
            /** @description Optional structured diagnostic context. */
            details?: unknown;
            /** @description Additional structured diagnostics associated with the failure. */
            diagnostics?: components["schemas"]["PluginDiagnosticResponse"][];
            /** @description 错误说明。 */
            error: string;
            /** @description Whether retrying the same operation may succeed. */
            retryable?: boolean | null;
        };
        /**
         * @description 执行资源动作请求。
         * @example {
         *       "input": {
         *         "mode": "default"
         *       }
         *     }
         */
        ExecuteResourceActionRequest: {
            /** @description 传递给插件 action handler 的 JSON 输入。 */
            input?: unknown;
        };
        GrantDirectoryRequest: {
            directory: string;
            permission: string;
            user_id: string;
        };
        HealthComponentResponse: {
            status: string;
        };
        /** @description 健康检查响应。 */
        HealthResponse: {
            blob_storage: components["schemas"]["HealthComponentResponse"];
            database: components["schemas"]["HealthComponentResponse"];
            /** @description 服务状态。 */
            status: string;
        };
        ManagedUserResponse: {
            id: string;
            role: string;
            status: string;
            username: string;
            workspace_directory: string;
        };
        MeResponse: {
            user: components["schemas"]["AuthenticatedUser"];
        };
        /** @description 插件或宿主产生的结构化诊断信息。 */
        PluginDiagnosticResponse: {
            code: string;
            details?: unknown;
            message: string;
            retryable: boolean;
            severity: string;
        };
        /** @description 资源动作适用范围。 */
        ResourceActionAppliesToResponse: {
            extensions: string[];
            kinds: string[];
            mime_types: string[];
        };
        /** @description 资源动作定义响应。 */
        ResourceActionDefinitionResponse: {
            /** @description 访问边界。 */
            access: string;
            /** @description 资源和内容匹配条件。 */
            applies_to: components["schemas"]["ResourceActionAppliesToResponse"];
            /** @description 动作说明。 */
            description?: string | null;
            /** @description 执行器声明。 */
            executor: components["schemas"]["ResourceActionExecutorResponse"];
            /** @description 动作 ID。 */
            id: string;
            /** @description 展示名称。 */
            label: string;
            /** @description 输出约定。 */
            output: components["schemas"]["ResourceActionOutputContractResponse"];
            /** @description 动作所需数据。 */
            requires: components["schemas"]["ResourceActionRequirementsResponse"];
            /** @description UI 展示提示。 */
            ui: components["schemas"]["ResourceActionUiResponse"];
        };
        ResourceActionExecutorResponse: {
            handler?: string | null;
            type: string;
        };
        ResourceActionOutputContractResponse: {
            view: string[];
        };
        /** @description 执行资源动作响应。 */
        ResourceActionOutputResponse: {
            /** @description 动作 ID。 */
            action: string;
            /** @description 插件返回的非致命诊断信息。 */
            diagnostics: components["schemas"]["PluginDiagnosticResponse"][];
            /** @description 资源唯一标识。 */
            resource_id: string;
            /** @description 插件返回的 View。 */
            view: unknown;
        };
        ResourceActionRequirementsResponse: {
            content: boolean;
            content_delivery: string;
        };
        ResourceActionUiResponse: {
            group?: string | null;
            locations: string[];
            /** Format: int32 */
            order?: number | null;
        };
        /** @description 资源允许的操作集合。 */
        ResourceActionsResponse: {
            /** @description 当前资源允许的动作。 */
            available_actions: components["schemas"]["ResourceActionDefinitionResponse"][];
        };
        /** @description 内容匹配条件。 */
        ResourceContentMatcherResponse: {
            /** @description 匹配的文件扩展名。 */
            extensions: string[];
            /** @description 匹配的 MIME 类型，支持 `image/*` 这类通配前缀。 */
            mime_types: string[];
        };
        /** @description 资源内容引用响应。 */
        ResourceContentResponse: {
            /** @description 内容校验和集合。 */
            checksum: components["schemas"]["ChecksumResponse"];
            /** @description 内容 MIME 类型。 */
            mime_type?: string | null;
            /**
             * Format: int64
             * @description 内容字节大小。
             */
            size: number;
        };
        /** @description 逻辑目录响应。 */
        ResourceDirectoryResponse: {
            /** @description 当前目录名。 */
            name: string;
            /** @description 父目录路径。 */
            parent_path: string;
            /** @description 目录完整路径。 */
            path: string;
        };
        /** @description 资源类型专属元数据响应。 */
        ResourceKindMetadataResponse: {
            data: unknown;
            kind: string;
            /** Format: int32 */
            schema_version: number;
        };
        /** @description 资源类型响应。 */
        ResourceKindResponse: {
            /** @description kind 支持的动作。 */
            actions: components["schemas"]["ResourceActionDefinitionResponse"][];
            /** @description 从直接父类型到根类型的完整祖先链。 */
            ancestors: string[];
            detect?: null | components["schemas"]["ResourceContentMatcherResponse"];
            /** @description 资源类型值。 */
            kind: string;
            /** @description 展示名称。 */
            label: string;
            /** @description 直接父类型；根类型为 null。 */
            parent?: string | null;
            /** @description 定义来源：`builtin`、`config` 或 `plugin:<id>`。 */
            source: string;
            /** @description 是否允许上传文件内容。 */
            supports_content: boolean;
        };
        /** @description 资源类型列表响应。 */
        ResourceKindsResponse: {
            /** @description 当前后端支持的资源类型。 */
            items: components["schemas"]["ResourceKindResponse"][];
        };
        /**
         * @description 创建或上传资源时可传入的资源元数据。
         * @example {
         *       "summary": {
         *         "description": "Human readable resource description",
         *         "tags": [
         *           "demo",
         *           "asset"
         *         ]
         *       }
         *     }
         */
        ResourceMetadataRequest: {
            summary?: null | components["schemas"]["ResourceSummaryMetadataRequest"];
        };
        /**
         * @description 资源元数据响应。
         * @example {
         *       "summary": {
         *         "description": "Human readable resource description",
         *         "tags": [
         *           "demo",
         *           "asset"
         *         ]
         *       },
         *       "kind_metadata": null
         *     }
         */
        ResourceMetadataResponse: {
            /** @description 当前 kind 的扩展元数据；尚未定义时为 null。 */
            kind_metadata?: null | components["schemas"]["ResourceKindMetadataResponse"];
            /** @description 核心摘要元数据。 */
            summary: components["schemas"]["ResourceSummaryMetadataResponse"];
        };
        /** @description 资源分页响应。 */
        ResourcePageResponse: {
            /** @description 当前页资源。 */
            items: components["schemas"]["ResourceResponse"][];
            /**
             * Format: int32
             * @description 每页数量。
             */
            limit: number;
            /**
             * Format: int32
             * @description 当前页码，从 1 开始。
             */
            page: number;
            /**
             * Format: int64
             * @description 符合条件的总记录数。
             */
            total: number;
        };
        /** @description 在线阅读响应。 */
        ResourceReadResponse: {
            /** @description 资源唯一标识。 */
            id: string;
            /** @description 资源类型。 */
            kind: string;
            /** @description 资源展示名。 */
            name: string;
            /** @description 插件返回的 View。 */
            view: unknown;
        };
        /** @description 资源响应。 */
        ResourceResponse: {
            /** @description 当前资源允许的操作。 */
            actions: components["schemas"]["ResourceActionsResponse"];
            content?: null | components["schemas"]["ResourceContentResponse"];
            /** @description 资源创建时间，RFC3339 格式。 */
            created_at: string;
            /** @description 软删除时间，RFC3339 格式；为空表示未删除。 */
            deleted_at?: string | null;
            /** @description 资源所在逻辑目录，根目录为空字符串。 */
            directory: string;
            /** @description 资源唯一标识。 */
            id: string;
            /** @description 资源类型。 */
            kind: string;
            /** @description 资源元数据。 */
            metadata: components["schemas"]["ResourceMetadataResponse"];
            /** @description 资源展示名。 */
            name: string;
            /** @description 资源生命周期状态。 */
            status: string;
            /** @description 资源最后更新时间，RFC3339 格式。 */
            updated_at: string;
        };
        /** @description 创建或上传资源时可传入的核心摘要元数据。 */
        ResourceSummaryMetadataRequest: {
            /** @description 资源描述。 */
            description?: string | null;
            /** @description 资源标签。 */
            tags?: string[] | null;
        };
        /** @description 资源核心摘要元数据响应。 */
        ResourceSummaryMetadataResponse: {
            /** @description 资源描述。 */
            description?: string | null;
            /** @description 资源标签。 */
            tags: string[];
        };
        /** @description 单文件扫描失败响应。 */
        ScanStorageErrorResponse: {
            /** @description 失败原因。 */
            error: string;
            /** @description 内容存储键。 */
            key: string;
        };
        /**
         * @description 扫描对象存储前缀请求。
         * @example {
         *       "prefix": "uploads"
         *     }
         */
        ScanStorageRequest: {
            /** @description 可选对象键前缀；未提供时扫描整个对象存储根命名空间。 */
            prefix?: string;
        };
        /** @description 扫描本地对象存储目录响应。 */
        ScanStorageResponse: {
            /** @description 单文件失败信息。 */
            errors: components["schemas"]["ScanStorageErrorResponse"][];
            /**
             * Format: int64
             * @description 新导入的资源数量。
             */
            imported: number;
            /** @description 本次新导入的资源。 */
            resources: components["schemas"]["ResourceResponse"][];
            /**
             * Format: int64
             * @description 扫描到的普通文件数量。
             */
            scanned: number;
            /** @description 本次扫描覆盖的对象存储前缀。字段名为兼容旧客户端而保留。 */
            scanned_directory: string;
            /**
             * Format: int64
             * @description 因已存在或导入失败而跳过的数量。
             */
            skipped: number;
        };
        SecurityAuditEventResponse: {
            actor_user_id?: string | null;
            actor_username?: string | null;
            event_type: string;
            /** Format: int64 */
            id: number;
            method: string;
            occurred_at: string;
            outcome: string;
            path: string;
            /** Format: int32 */
            status_code: number;
            target?: string | null;
        };
        /**
         * @description 更新资源请求。
         * @example {
         *       "name": "renamed.txt",
         *       "kind": "core:unknown",
         *       "status": "archived",
         *       "metadata": {
         *         "summary": {
         *           "description": "updated resource",
         *           "tags": [
         *             "demo",
         *             "updated"
         *           ]
         *         }
         *       }
         *     }
         */
        UpdateResourceRequest: {
            /** @description 可选新逻辑目录；根目录为空字符串。 */
            directory?: string | null;
            /** @description 可选新资源类型。 */
            kind?: string | null;
            metadata?: null | components["schemas"]["ResourceMetadataRequest"];
            /** @description 可选新资源展示名。 */
            name?: string | null;
            /** @description 是否恢复软删除资源。 */
            restore?: boolean | null;
            /** @description 可选新状态：`active` 或 `archived`。 */
            status?: string | null;
        };
        UpdateUserStatusRequest: {
            status: string;
        };
        /**
         * @description 上传内容并创建资源请求。
         *     流式上传内容并创建资源的 query 参数。
         */
        UploadResourceContentStreamQuery: {
            /** @description 可选上传目录。 */
            directory?: string | null;
            /** @description 可选资源类型。 */
            kind?: string | null;
            /** @description 可选 JSON 字符串形式的资源元数据，结构与 `ResourceMetadataRequest` 一致。 */
            metadata_json?: string | null;
            /** @description 资源文件名；与目录共同决定对象存储路径。 */
            name: string;
            /** @description 可选初始状态：`active` 或 `archived`。 */
            status?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    audit_storage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditStorageRequest"];
            };
        };
        responses: {
            /** @description 审计结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditStorageResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_security_audit_events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page: number | null;
                limit: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityAuditEventResponse"][];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    my_directory_grants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryGrantResponse"][];
                };
            };
        };
    };
    grant_directory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantDirectoryRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke_directory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                directory: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many failed attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedUserResponse"][];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_user_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserStatusRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedUserResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_directory: {
        parameters: {
            query?: {
                /** @description 当前目录路径；根目录为空字符串。 */
                path?: string;
                /** @description 资源页码，从 1 开始。 */
                page?: number;
                /** @description 每页资源数量。 */
                limit?: number;
                /** @description 可选资源类型过滤。 */
                kind?: string;
                /** @description kind 过滤是否包含所有后代类型。 */
                include_descendants?: boolean;
                /** @description 可选标签过滤。 */
                tag?: string;
                /** @description 可选名称模糊搜索关键字。 */
                q?: string;
                /** @description 是否包含软删除资源。 */
                include_deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 目录列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryListingResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_directory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDirectoryRequest"];
            };
        };
        responses: {
            /** @description 目录已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceDirectoryResponse"];
                };
            };
            /** @description 目录名称无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 没有父目录写权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务就绪 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description 数据库或对象存储不可用 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_resource_kinds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源类型列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceKindsResponse"];
                };
            };
        };
    };
    list_resources: {
        parameters: {
            query?: {
                /** @description 页码，从 1 开始。 */
                page?: number;
                /** @description 每页数量。 */
                limit?: number;
                /** @description 可选资源类型过滤。 */
                kind?: string;
                /** @description kind 过滤是否包含所有后代类型。 */
                include_descendants?: boolean;
                /** @description 可选标签过滤。 */
                tag?: string;
                /** @description 可选名称模糊搜索关键字。 */
                q?: string;
                /** @description 可选逻辑目录过滤；根目录为空字符串。 */
                directory?: string;
                /** @description 是否包含软删除资源。 */
                include_deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourcePageResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_resource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResourceRequest"];
            };
        };
        responses: {
            /** @description 资源已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_resource_content_stream: {
        parameters: {
            query: {
                /** @description 资源文件名；与目录共同决定对象存储路径。 */
                name: string;
                /** @description 可选上传目录。 */
                directory?: string;
                /** @description 可选资源类型。 */
                kind?: string;
                /** @description 可选初始状态：`active` 或 `archived`。 */
                status?: string;
                /** @description 可选 JSON 字符串形式的资源元数据，结构与 `ResourceMetadataRequest` 一致。 */
                metadata_json?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 原始二进制内容流 */
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description 资源内容已流式上传并创建资源 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    find_resource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    soft_delete_resource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源已软删除 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_resource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateResourceRequest"];
            };
        };
        responses: {
            /** @description 资源已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    execute_resource_action: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
                /** @description 动作 ID */
                action: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteResourceActionRequest"];
            };
        };
        responses: {
            /** @description 动作执行结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceActionOutputResponse"];
                };
            };
            /** @description 资源类型不支持该动作或动作未配置 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 插件或服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_resource_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源原始内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": components["schemas"]["BinaryContent"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源内容不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    preview_resource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源预览内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": components["schemas"]["BinaryContent"];
                };
            };
            /** @description 资源类型不支持预览 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源或内容不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    remove_resource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源和对象内容已物理移除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_resource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源阅读内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceReadResponse"];
                };
            };
            /** @description 资源类型不支持阅读或内容格式不支持 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源或内容不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    thumbnail_resource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源缩略图 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": components["schemas"]["BinaryContent"];
                };
            };
            /** @description 资源类型不支持缩略图 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源或内容不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    scan_storage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanStorageRequest"];
            };
        };
        responses: {
            /** @description 扫描结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanStorageResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
