/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_users"];
        put?: never;
        post: operations["create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_user_status"];
        trace?: never;
    };
    "/directories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出当前目录的直接子目录和资源。 */
        get: operations["list_directory"];
        put?: never;
        /** 创建一个与存储侧实体对应的空目录。 */
        post: operations["create_directory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/directories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按稳定 ID 查询目录。 */
        get: operations["find_directory"];
        put?: never;
        post?: never;
        /** 删除空目录。根目录和非空目录不可删除。 */
        delete: operations["delete_directory"];
        options?: never;
        head?: never;
        /** 以乐观并发方式更新目录元数据或父目录。 */
        patch: operations["update_directory"];
        trace?: never;
    };
    "/directories/{id}/actions/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 执行目录插件动作。 */
        post: operations["execute_directory_action"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/directories/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a directory tree as a ZIP archive. */
        get: operations["download_directory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/directory-kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出当前后端支持的目录类型。 */
        get: operations["list_directory_kinds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查。 */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resource-kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出当前后端支持的资源类型。 */
        get: operations["list_resource_kinds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页列出资源。 */
        get: operations["list_resources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按 ID 查询资源。 */
        get: operations["find_resource"];
        put?: never;
        post?: never;
        /** 软删除资源。 */
        delete: operations["soft_delete_resource"];
        options?: never;
        head?: never;
        /** 更新资源。 */
        patch: operations["update_resource"];
        trace?: never;
    };
    "/resources/{id}/actions/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 执行资源插件动作。 */
        post: operations["execute_resource_action"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取资源内容。 */
        get: operations["get_resource_content"];
        /** 流式替换资源文本内容。 */
        put: operations["replace_resource_content"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 下载资源内容。 */
        get: operations["download_resource_content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 物理移除资源和对象内容。 */
        delete: operations["remove_resource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["upload_status"];
        put?: never;
        post?: never;
        delete: operations["abort_upload"];
        options?: never;
        head?: never;
        patch: operations["append_upload"];
        trace?: never;
    };
    "/uploads/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["complete_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthenticatedUser: {
            id: string;
            is_admin: boolean;
            username: string;
        };
        /**
         * Format: binary
         * @description OpenAPI 中表示原始二进制请求或响应体的 schema。
         */
        BinaryContent: string;
        /** @description 内容校验和响应。 */
        ChecksumResponse: {
            /** @description 校验和算法类型。 */
            kind: string;
            /** @description 校验和值。 */
            value: string;
        };
        /**
         * @description 内容校验状态响应。
         * @enum {string}
         */
        ContentVerificationStatusResponse: "pending" | "verified" | "failed";
        /** @description 创建逻辑目录请求。 */
        CreateDirectoryRequest: {
            /** @description 可选目录类型。 */
            kind?: string | null;
            /** @description 新目录名称，只允许单个路径段。 */
            name: string;
            /** @description Stable parent Directory ID. */
            parent_id: string;
        };
        /** @description 创建断点续传会话。 */
        CreateUploadRequest: {
            directory?: string;
            /** @description 客户端对完整本地文件增量计算出的 SHA-256。 */
            expected_sha256: string;
            kind?: string | null;
            mime_type?: string | null;
            name: string;
            /** Format: int64 */
            size: number;
        };
        CreateUserRequest: {
            is_admin?: boolean;
            password: string;
            username: string;
            workspace_directory?: string | null;
        };
        Credentials: {
            password: string;
            username: string;
        };
        DefinitionOriginResponse: {
            id: string;
            kind: string;
        };
        DirectoryActionAppliesToResponse: {
            kinds: string[];
        };
        DirectoryActionDefinitionResponse: {
            access: string;
            applies_to: components["schemas"]["DirectoryActionAppliesToResponse"];
            description?: string | null;
            id: string;
            label: string;
            origin: components["schemas"]["DefinitionOriginResponse"];
            output: components["schemas"]["ResourceActionOutputContractResponse"];
            provides?: string | null;
            requires: components["schemas"]["DirectoryActionRequirementsResponse"];
            ui: components["schemas"]["ResourceActionUiResponse"];
        };
        DirectoryActionOutputResponse: {
            action: string;
            diagnostics: components["schemas"]["PluginDiagnosticResponse"][];
            directory_id: string;
            view: unknown;
        };
        DirectoryActionRequirementsResponse: {
            children: boolean;
            resources: boolean;
        };
        DirectoryKindResponse: {
            actions: components["schemas"]["DirectoryActionDefinitionResponse"][];
            ancestors: string[];
            kind: string;
            label: string;
            origin: components["schemas"]["DefinitionOriginResponse"];
            parent?: string | null;
        };
        DirectoryKindsResponse: {
            items: components["schemas"]["DirectoryKindResponse"][];
        };
        /** @description 目录浏览响应。 */
        DirectoryListingResponse: {
            /** @description 当前目录。 */
            directory: components["schemas"]["DirectoryResponse"];
            /** @description 直接子目录。 */
            folders: components["schemas"]["DirectoryResponse"][];
            /** @description 相对于当前用户可见根目录的当前路径。 */
            path: string;
            /** @description 当前目录下的资源分页。 */
            resources: components["schemas"]["ResourcePageResponse"];
        };
        /** @description 逻辑目录响应。 */
        DirectoryResponse: {
            actions: components["schemas"]["DirectoryActionDefinitionResponse"][];
            created_at: string;
            /** @description 稳定目录标识；目录移动或重命名后保持不变。 */
            id: string;
            kind: string;
            /** @description 当前目录名。 */
            name: string;
            parent_id?: string | null;
            /** @description 相对于当前用户可见根目录的父路径。 */
            parent_path: string;
            /** @description 相对于当前用户可见根目录的路径。 */
            path: string;
            /** Format: int64 */
            revision: number;
            updated_at: string;
        };
        /** @description 统一 HTTP 错误响应。 */
        ErrorResponse: {
            /** @description Stable machine-readable error code when available. */
            code?: string | null;
            /** @description Optional structured diagnostic context. */
            details?: unknown;
            /** @description Additional structured diagnostics associated with the failure. */
            diagnostics?: components["schemas"]["PluginDiagnosticResponse"][];
            /** @description 错误说明。 */
            error: string;
            /** @description Whether retrying the same operation may succeed. */
            retryable?: boolean | null;
        };
        ExecuteDirectoryActionRequest: {
            /**
             * Format: int64
             * @description Optional for read actions and required for write actions.
             */
            expected_revision?: number | null;
            input?: unknown;
        };
        /**
         * @description 执行资源动作请求。
         * @example {
         *       "expected_revision": 7,
         *       "input": {
         *         "mode": "default"
         *       }
         *     }
         */
        ExecuteResourceActionRequest: {
            /**
             * Format: int64
             * @description Optional for read actions and required for write actions.
             */
            expected_revision?: number | null;
            /** @description 传递给插件 action handler 的 JSON 输入。 */
            input?: unknown;
        };
        HealthComponentResponse: {
            status: string;
        };
        /** @description 健康检查响应。 */
        HealthResponse: {
            blob_storage: components["schemas"]["HealthComponentResponse"];
            database: components["schemas"]["HealthComponentResponse"];
            session_store?: null | components["schemas"]["HealthComponentResponse"];
            /** @description 服务状态。 */
            status: string;
        };
        ManagedUserResponse: {
            id: string;
            role: string;
            status: string;
            username: string;
            workspace_directory: string;
        };
        MeResponse: {
            user: components["schemas"]["AuthenticatedUser"];
        };
        /** @description 插件或宿主产生的结构化诊断信息。 */
        PluginDiagnosticResponse: {
            code: string;
            details?: unknown;
            message: string;
            retryable: boolean;
            severity: string;
        };
        /** @description 资源动作适用范围。 */
        ResourceActionAppliesToResponse: {
            extensions: string[];
            kinds: string[];
            mime_types: string[];
        };
        /** @description 资源动作定义响应。 */
        ResourceActionDefinitionResponse: {
            /** @description 访问边界。 */
            access: string;
            /** @description 资源和内容匹配条件。 */
            applies_to: components["schemas"]["ResourceActionAppliesToResponse"];
            /** @description 动作说明。 */
            description?: string | null;
            /** @description 动作 ID。 */
            id: string;
            /** @description 展示名称。 */
            label: string;
            origin: components["schemas"]["DefinitionOriginResponse"];
            /** @description 输出约定。 */
            output: components["schemas"]["ResourceActionOutputContractResponse"];
            /** @description 此 Action 实现的单例 Host 能力。 */
            provides?: string | null;
            /** @description 动作所需数据。 */
            requires: components["schemas"]["ResourceActionRequirementsResponse"];
            /** @description UI 展示提示。 */
            ui: components["schemas"]["ResourceActionUiResponse"];
        };
        ResourceActionOutputContractResponse: {
            views: string[];
        };
        /** @description 执行资源动作响应。 */
        ResourceActionOutputResponse: {
            /** @description 动作 ID。 */
            action: string;
            /** @description 插件返回的非致命诊断信息。 */
            diagnostics: components["schemas"]["PluginDiagnosticResponse"][];
            /** @description 资源唯一标识。 */
            resource_id: string;
            /** @description 插件返回的 View。 */
            view: unknown;
        };
        ResourceActionRequirementsResponse: {
            content: boolean;
            content_delivery: string;
        };
        ResourceActionUiResponse: {
            group?: string | null;
            locations: string[];
            /** Format: int32 */
            order?: number | null;
        };
        /** @description 内容匹配条件。 */
        ResourceContentMatcherResponse: {
            /** @description 匹配的文件扩展名。 */
            extensions: string[];
            /** @description 匹配的 MIME 类型，支持 `image/*` 这类通配前缀。 */
            mime_types: string[];
        };
        /** @description 资源内容引用响应。 */
        ResourceContentResponse: {
            checksum?: null | components["schemas"]["ChecksumResponse"];
            /** @description 内容 MIME 类型。 */
            mime_type?: string | null;
            /**
             * Format: int64
             * @description 内容字节大小。
             */
            size: number;
            /** @description 后台校验失败原因；仅校验失败时存在。 */
            verification_error?: string | null;
            /** @description 内容校验状态。 */
            verification_status: components["schemas"]["ContentVerificationStatusResponse"];
        };
        /** @description 资源类型响应。 */
        ResourceKindResponse: {
            /** @description kind 支持的动作。 */
            actions: components["schemas"]["ResourceActionDefinitionResponse"][];
            /** @description 从直接父类型到根类型的完整祖先链。 */
            ancestors: string[];
            detect?: null | components["schemas"]["ResourceContentMatcherResponse"];
            /** @description 资源类型值。 */
            kind: string;
            /** @description 展示名称。 */
            label: string;
            /** @description 定义来源：`builtin`、`config` 或 `plugin:<id>`。 */
            origin: components["schemas"]["DefinitionOriginResponse"];
            /** @description 直接父类型；根类型为 null。 */
            parent?: string | null;
            /** @description 是否允许上传文件内容。 */
            supports_content: boolean;
        };
        /** @description 资源类型列表响应。 */
        ResourceKindsResponse: {
            /** @description 当前后端支持的资源类型。 */
            items: components["schemas"]["ResourceKindResponse"][];
        };
        /** @description 资源分页响应。 */
        ResourcePageResponse: {
            /** @description 当前页资源。 */
            items: components["schemas"]["ResourceResponse"][];
            /**
             * Format: int32
             * @description 每页数量。
             */
            limit: number;
            /**
             * Format: int32
             * @description 当前页码，从 1 开始。
             */
            page: number;
            /**
             * Format: int64
             * @description 符合条件的总记录数。
             */
            total: number;
        };
        /** @description 资源响应。 */
        ResourceResponse: {
            /** @description 当前资源允许的操作。 */
            actions: components["schemas"]["ResourceActionDefinitionResponse"][];
            content?: null | components["schemas"]["ResourceContentResponse"];
            /** @description 资源创建时间，RFC3339 格式。 */
            created_at: string;
            /** @description 软删除时间，RFC3339 格式；为空表示未删除。 */
            deleted_at?: string | null;
            /** @description 相对于当前用户可见根目录的路径；根目录为空字符串。 */
            directory: string;
            /** @description 资源唯一标识。 */
            id: string;
            /** @description 资源类型。 */
            kind: string;
            /** @description 资源展示名。 */
            name: string;
            /**
             * Format: int64
             * @description 单调递增的资源聚合版本。
             */
            revision: number;
            /** @description 资源最后更新时间，RFC3339 格式。 */
            updated_at: string;
        };
        UpdateDirectoryRequest: {
            /** Format: int64 */
            expected_revision: number;
            kind?: string | null;
            name?: string | null;
            parent_id?: string | null;
        };
        /**
         * @description 更新资源请求。
         * @example {
         *       "name": "renamed.txt",
         *       "kind": "core:resource"
         *     }
         */
        UpdateResourceRequest: {
            /** @description 相对于当前用户可见根目录的新路径；根目录为空字符串。 */
            directory?: string | null;
            /**
             * Format: int64
             * @description Required optimistic-concurrency precondition.
             */
            expected_revision: number;
            /** @description 可选新资源类型。 */
            kind?: string | null;
            /** @description 可选新资源展示名。 */
            name?: string | null;
            /** @description 是否恢复软删除资源。 */
            restore?: boolean | null;
        };
        UpdateUserStatusRequest: {
            status: string;
        };
        UploadSessionResponse: {
            /** @description 后台 finalization 的失败原因。 */
            error?: string | null;
            id: string;
            /** Format: int64 */
            offset: number;
            /** @description finalization 完成后创建的 Resource ID。 */
            resource_id?: string | null;
            /** Format: int64 */
            size: number;
            /** @description uploading、finalizing、completed 或 failed。 */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many failed attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedUserResponse"][];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_user_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserStatusRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedUserResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_directory: {
        parameters: {
            query?: {
                /** @description 相对于当前用户可见根目录的路径；根目录为空字符串。 */
                path?: string;
                /** @description 资源页码，从 1 开始。 */
                page?: number;
                /** @description 每页资源数量。 */
                limit?: number;
                /** @description 可选资源类型过滤。 */
                kind?: string;
                /** @description 可选名称模糊搜索关键字。 */
                q?: string;
                /** @description 是否包含软删除资源。 */
                include_deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 目录列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryListingResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_directory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDirectoryRequest"];
            };
        };
        responses: {
            /** @description 目录已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryResponse"];
                };
            };
            /** @description 目录名称无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 没有父目录写权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    find_directory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 目录 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 目录详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryResponse"];
                };
            };
            /** @description 目录 ID 无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 没有目录读取权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目录不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_directory: {
        parameters: {
            query: {
                expected_revision: number;
            };
            header?: never;
            path: {
                /** @description 目录 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 空目录已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 目录 ID 无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 没有目录删除权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目录不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目录非空或版本已变化 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_directory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 目录 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDirectoryRequest"];
            };
        };
        responses: {
            /** @description 目录已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 没有目录写权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目录或父目录不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目录版本冲突或目标位置冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    execute_directory_action: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                action: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteDirectoryActionRequest"];
            };
        };
        responses: {
            /** @description 动作执行结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryActionOutputResponse"];
                };
            };
            /** @description 目录类型不支持该动作 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目录不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    download_directory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Directory ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directory ZIP archive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": components["schemas"]["BinaryContent"];
                };
            };
            /** @description Invalid directory ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Directory is outside the current workspace */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Directory or resource content not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Archive generation failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_directory_kinds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 目录类型列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryKindsResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务就绪 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description 数据库、Session 存储或对象存储不可用 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_resource_kinds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源类型列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceKindsResponse"];
                };
            };
        };
    };
    list_resources: {
        parameters: {
            query?: {
                /** @description 页码，从 1 开始。 */
                page?: number;
                /** @description 每页数量。 */
                limit?: number;
                /** @description 可选资源类型过滤。 */
                kind?: string;
                /** @description 可选名称模糊搜索关键字。 */
                q?: string;
                /** @description 相对于当前用户可见根目录的过滤路径；根目录为空字符串。 */
                directory?: string;
                /** @description 是否包含软删除资源。 */
                include_deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourcePageResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    find_resource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    soft_delete_resource: {
        parameters: {
            query: {
                expected_revision: number;
            };
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源已软删除 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源版本已变化 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_resource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateResourceRequest"];
            };
        };
        responses: {
            /** @description 资源已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    execute_resource_action: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
                /** @description 动作 ID */
                action: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteResourceActionRequest"];
            };
        };
        responses: {
            /** @description 动作执行结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceActionOutputResponse"];
                };
            };
            /** @description 资源类型不支持该动作或动作未配置 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源版本已变化 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 插件或服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_resource_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源原始内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": components["schemas"]["BinaryContent"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源内容不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    replace_resource_content: {
        parameters: {
            query?: never;
            header: {
                /** @description 带双引号的资源 revision */
                "If-Match": string;
                /** @description 64 位小写十六进制 SHA-256 */
                "Content-SHA256": string;
                /** @description 原始内容字节数 */
                "Content-Length": number;
            };
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        /** @description 替换后的原始 UTF-8 文本字节 */
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description 资源内容已替换 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceResponse"];
                };
            };
            /** @description 请求头或资源状态无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 当前工作区没有写权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源 revision、大小或摘要冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 文本超过 Host 编辑上限 */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    download_resource_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源下载流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": components["schemas"]["BinaryContent"];
                };
            };
            /** @description 资源部分下载流 */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": components["schemas"]["BinaryContent"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源内容不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    remove_resource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源和对象内容已物理移除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        responses: {
            /** @description 上传会话已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目标路径冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 上传会话 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 上传偏移和后台 finalization 状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionResponse"];
                };
            };
            /** @description 上传会话不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    abort_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 上传会话 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 上传会话及临时内容已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 上传会话不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    append_upload: {
        parameters: {
            query?: never;
            header: {
                /** @description 本分片起始偏移 */
                "Upload-Offset": number;
                /** @description 本分片的 64 位小写十六进制 SHA-256 */
                "Upload-Checksum": string;
            };
            path: {
                /** @description 上传会话 ID */
                id: string;
            };
            cookie?: never;
        };
        /** @description 从 Upload-Offset 开始的原始文件分片 */
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description 分片已持久化 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 上传偏移或分片摘要冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    complete_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 上传会话 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 后台 finalization 已接受 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionResponse"];
                };
            };
            /** @description 上传不完整或目标路径冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
