[package]
name = "asset-infra"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
asset-plugin-api.workspace = true
asset-core.workspace = true

async-trait.workspace = true
argon2.workspace = true
base64.workspace = true
bytes.workspace = true
chrono.workspace = true
config.workspace = true
extism.workspace = true
futures-core.workspace = true
futures-util.workspace = true
opendal.workspace = true
serde.workspace = true
serde_json.workspace = true
jsonschema.workspace = true
sha2.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
