[workspace]
resolver = "3"
members = ["asset-config", "asset-config-macros", "core", "utils"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/AzVs32/asset-hub"
authors = ["AzVs"]

[workspace.dependencies]
utils = { path = "utils" }
uuid = { version = "1.26.1", features = ["v7", "serde"] }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
getset = "0.1.7"
config = { version = "0.15.25", default-features = false, features = ["toml"] }
linkme = "0.3.37"
proc-macro2 = "1.0.107"
proc-macro-crate = "3.5.0"
quote = "1.0.47"
syn = { version = "3.0.6", features = ["full"] }
