// Generated by `cargo run -p asset-plugin-api --example export_contract`; do not edit.
// biome-ignore-all format: generated contract catalog
export const PLUGIN_API_VERSION = "asset-hub.plugin-api@3" as const;
export const RESOURCE_FRAME_CHANNEL = "asset-hub.plugin-frame.resource@3" as const;
export const DIRECTORY_FRAME_CHANNEL = "asset-hub.plugin-frame.directory@3" as const;
export const resourceActionCapabilityIds = ["thumbnail","view","edit"] as const;
export const directoryActionCapabilityIds = ["thumbnail","workspace"] as const;
export const resourceFrameMethods = ["executeResourceAction","replaceResourceText"] as const;
export const directoryFrameMethods = ["executeDirectoryAction","viewResource","refreshDirectory","navigateToDirectory","editResource"] as const;
export const pluginViewKinds = ["text","markdown","html","plugin_frame","json","media","download"] as const;
export const resourceActionEffectKinds = ["replace_content","delete"] as const;
export const directoryActionEffectKinds = ["update","create_child","create_tree","delete"] as const;
