/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/directories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出当前目录的直接子目录和资源。 */
        get: operations["list_directory"];
        put?: never;
        /** 创建一个与存储侧实体对应的空目录。 */
        post: operations["create_directory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/directories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按稳定 ID 查询目录。 */
        get: operations["find_directory"];
        put?: never;
        post?: never;
        /** 删除空目录。根目录和非空目录不可删除。 */
        delete: operations["delete_directory"];
        options?: never;
        head?: never;
        /** 以乐观并发方式更新目录元数据或父目录。 */
        patch: operations["update_directory"];
        trace?: never;
    };
    "/directories/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a directory tree as a ZIP archive. */
        get: operations["download_directory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查。 */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页列出资源。 */
        get: operations["list_resources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按 ID 查询资源。 */
        get: operations["find_resource"];
        put?: never;
        post?: never;
        /** Permanently delete a Resource and its physical content. */
        delete: operations["delete_resource"];
        options?: never;
        head?: never;
        /** 更新资源。 */
        patch: operations["update_resource"];
        trace?: never;
    };
    "/resources/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取资源内容。 */
        get: operations["get_resource_content"];
        /** 流式替换资源文本内容。 */
        put: operations["replace_resource_content"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 下载资源内容。 */
        get: operations["download_resource_content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["upload_status"];
        put?: never;
        post?: never;
        delete: operations["abort_upload"];
        options?: never;
        head?: never;
        patch: operations["append_upload"];
        trace?: never;
    };
    "/uploads/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["complete_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: binary
         * @description OpenAPI 中表示原始二进制请求或响应体的 schema。
         */
        BinaryContent: string;
        /** @description 内容校验和响应。 */
        ChecksumResponse: {
            /** @description 校验和算法类型。 */
            kind: string;
            /** @description 校验和值。 */
            value: string;
        };
        /** @description 创建逻辑目录请求。 */
        CreateDirectoryRequest: {
            /** @description 新目录名称，只允许单个路径段。 */
            name: string;
            /** @description Stable global parent Directory ID. */
            parent_id: string;
        };
        /** @description 创建断点续传会话。 */
        CreateUploadRequest: {
            directory_id?: string;
            /** @description 客户端对完整本地文件增量计算出的 SHA-256。 */
            expected_sha256: string;
            mime_type?: string | null;
            name: string;
            /** Format: int64 */
            size: number;
        };
        /** @description 目录浏览响应。 */
        DirectoryListingResponse: {
            /** @description 当前目录。 */
            directory: components["schemas"]["DirectoryResponse"];
            /** @description 直接子目录。 */
            folders: components["schemas"]["DirectoryResponse"][];
            /** @description 相对于全局根目录的当前路径。 */
            path: string;
            /** @description 当前目录下的资源分页。 */
            resources: components["schemas"]["ResourcePageResponse"];
        };
        /** @description 逻辑目录响应。 */
        DirectoryResponse: {
            created_at: string;
            /** @description 稳定目录标识；目录移动或重命名后保持不变。 */
            id: string;
            /** @description 当前目录名。 */
            name: string;
            parent_id?: string | null;
            /** @description 相对于全局根目录的父路径。 */
            parent_path: string;
            /** @description 相对于全局根目录的路径。 */
            path: string;
            /** Format: int64 */
            revision: number;
            updated_at: string;
        };
        /** @description 统一 HTTP 错误响应。 */
        ErrorResponse: {
            /** @description Stable machine-readable error code when available. */
            code?: string | null;
            /** @description Optional structured diagnostic context. */
            details?: unknown;
            /** @description 错误说明。 */
            error: string;
            /** @description Whether retrying the same operation may succeed. */
            retryable?: boolean | null;
        };
        HealthComponentResponse: {
            status: string;
        };
        /** @description 健康检查响应。 */
        HealthResponse: {
            blob_storage: components["schemas"]["HealthComponentResponse"];
            database: components["schemas"]["HealthComponentResponse"];
            /** @description 服务状态。 */
            status: string;
        };
        /** @description 资源内容引用响应。 */
        ResourceContentResponse: {
            checksum?: null | components["schemas"]["ChecksumResponse"];
            /** @description 内容 MIME 类型。 */
            mime_type?: string | null;
            /**
             * Format: int64
             * @description 内容字节大小。
             */
            size: number;
            /** @description 后台校验失败原因；仅校验失败时存在。 */
            verification_error?: string | null;
        };
        /**
         * @description 资源是否包含对象内容及其校验状态。
         * @enum {string}
         */
        ResourceContentStateResponse: "absent" | "pending" | "verified" | "failed";
        /**
         * @description 需要单值状态判断的消费者所使用的统一有效状态。
         * @enum {string}
         */
        ResourceEffectiveStateResponse: "no_content" | "verifying" | "ready" | "verification_failed";
        /** @description 资源生命周期。 */
        ResourceLifecycleStateResponse: {
            /** @enum {string} */
            status: "active";
        };
        /** @description 资源分页响应。 */
        ResourcePageResponse: {
            /** @description 当前页资源。 */
            items: components["schemas"]["ResourceResponse"][];
            /**
             * Format: int32
             * @description 每页数量。
             */
            limit: number;
            /**
             * Format: int32
             * @description 当前页码，从 1 开始。
             */
            page: number;
            /**
             * Format: int64
             * @description 符合条件的总记录数。
             */
            total: number;
        };
        /** @description 资源响应。 */
        ResourceResponse: {
            content?: null | components["schemas"]["ResourceContentResponse"];
            /** @description 资源创建时间，RFC3339 格式。 */
            created_at: string;
            /** @description 相对于全局根目录的路径；根目录为空字符串。 */
            directory: string;
            /** @description Stable Directory identity; `directory` is the global relative display path. */
            directory_id: string;
            /** @description 资源唯一标识。 */
            id: string;
            /** @description 资源展示名。 */
            name: string;
            /**
             * Format: int64
             * @description 单调递增的资源聚合版本。
             */
            revision: number;
            /** @description 由 Core 统一派生的资源生命周期、内容和有效状态。 */
            state: components["schemas"]["ResourceStateResponse"];
            /** @description 资源最后更新时间，RFC3339 格式。 */
            updated_at: string;
        };
        /** @description 资源生命周期、内容和单值有效状态的统一响应。 */
        ResourceStateResponse: {
            content: components["schemas"]["ResourceContentStateResponse"];
            effective: components["schemas"]["ResourceEffectiveStateResponse"];
            lifecycle: components["schemas"]["ResourceLifecycleStateResponse"];
        };
        UpdateDirectoryRequest: {
            /** Format: int64 */
            expected_revision: number;
            name?: string | null;
            parent_id?: string | null;
        };
        /**
         * @description 更新资源请求。
         * @example {
         *       "name": "renamed.txt"
         *     }
         */
        UpdateResourceRequest: {
            /** @description Optional stable destination Directory UUID. */
            directory_id?: string | null;
            /**
             * Format: int64
             * @description Required optimistic-concurrency precondition.
             */
            expected_revision: number;
            /** @description 可选新资源展示名。 */
            name?: string | null;
        };
        UploadSessionResponse: {
            /** @description 后台 finalization 的失败原因。 */
            error?: string | null;
            id: string;
            /** Format: int64 */
            offset: number;
            /** @description finalization 完成后创建的 Resource ID。 */
            resource_id?: string | null;
            /** Format: int64 */
            size: number;
            /** @description uploading、finalizing、completed 或 failed。 */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_directory: {
        parameters: {
            query?: {
                /** @description 相对于全局根目录的路径；根目录为空字符串。 */
                path?: string;
                /** @description 资源页码，从 1 开始。 */
                page?: number;
                /** @description 每页资源数量。 */
                limit?: number;
                /** @description 可选名称模糊搜索关键字。 */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 目录列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryListingResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_directory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDirectoryRequest"];
            };
        };
        responses: {
            /** @description 目录已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryResponse"];
                };
            };
            /** @description 目录名称无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    find_directory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 目录 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 目录详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryResponse"];
                };
            };
            /** @description 目录 ID 无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目录不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_directory: {
        parameters: {
            query: {
                expected_revision: number;
            };
            header?: never;
            path: {
                /** @description 目录 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 空目录已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 目录 ID 无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目录不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目录非空或版本已变化 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_directory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 目录 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDirectoryRequest"];
            };
        };
        responses: {
            /** @description 目录已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目录或父目录不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目录版本冲突或目标位置冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    download_directory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Directory ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directory ZIP archive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": components["schemas"]["BinaryContent"];
                };
            };
            /** @description Invalid directory ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Directory or resource content not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Archive generation failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务就绪 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description 数据库或对象存储不可用 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_resources: {
        parameters: {
            query?: {
                /** @description 页码，从 1 开始。 */
                page?: number;
                /** @description 每页数量。 */
                limit?: number;
                /** @description 可选名称模糊搜索关键字。 */
                q?: string;
                /** @description 相对于全局根目录的过滤路径；根目录为空字符串。 */
                directory?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourcePageResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    find_resource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_resource: {
        parameters: {
            query: {
                expected_revision: number;
            };
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源已删除 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源版本已变化 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_resource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateResourceRequest"];
            };
        };
        responses: {
            /** @description 资源已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_resource_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源原始内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": components["schemas"]["BinaryContent"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源内容不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    replace_resource_content: {
        parameters: {
            query?: never;
            header: {
                /** @description 带双引号的资源 revision */
                "If-Match": string;
                /** @description 64 位小写十六进制 SHA-256 */
                "Content-SHA256": string;
                /** @description 原始内容字节数 */
                "Content-Length": number;
                /** @description 可选的幂等键，重复请求返回首次结果 */
                "Idempotency-Key"?: string | null;
            };
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        /** @description 替换后的原始 UTF-8 文本字节 */
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description 资源内容已替换 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceResponse"];
                };
            };
            /** @description 请求头或资源状态无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源 revision、大小或摘要冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 文本超过编辑大小上限 */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    download_resource_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源下载流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": components["schemas"]["BinaryContent"];
                };
            };
            /** @description 资源部分下载流 */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": components["schemas"]["BinaryContent"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 资源内容不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务端错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_upload: {
        parameters: {
            query?: never;
            header?: {
                /** @description 可选的幂等键，重复请求返回首次结果 */
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        responses: {
            /** @description 上传会话已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目标路径冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 上传会话 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 上传偏移和后台 finalization 状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionResponse"];
                };
            };
            /** @description 上传会话不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    abort_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 上传会话 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 上传会话及临时内容已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 上传会话不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    append_upload: {
        parameters: {
            query?: never;
            header: {
                /** @description 本分片起始偏移 */
                "Upload-Offset": number;
                /** @description 本分片的 64 位小写十六进制 SHA-256 */
                "Upload-Checksum": string;
            };
            path: {
                /** @description 上传会话 ID */
                id: string;
            };
            cookie?: never;
        };
        /** @description 从 Upload-Offset 开始的原始文件分片 */
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description 分片已持久化 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 上传偏移或分片摘要冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    complete_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 上传会话 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 后台 finalization 已接受 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionResponse"];
                };
            };
            /** @description 上传不完整或目标路径冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
