[package]
name = "asset-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
asset-core.workspace = true
asset-infra.workspace = true
tracing.workspace = true
tokio.workspace = true

[dev-dependencies]
bytes.workspace = true
futures-util.workspace = true
sha2.workspace = true
