#[derive(Debug, thiserror::Error)]
pub enum ConfigError {
    /// An error generated by the `config crate` itself.
    #[error(transparent)]
    Backend(#[from] config::ConfigError),

    /// A configuration section uses the same key as, or overlaps, another section.
    #[error("config key `{incoming}` conflicts with registered key `{existing}`")]
    KeyConflict {
        existing: &'static str,
        incoming: &'static str,
    },

    /// A section key is not a dot-separated path of bare key segments.
    #[error(
        "invalid config key `{0}`: use non-empty dot-separated segments containing only ASCII letters, digits, `_`, or `-`"
    )]
    InvalidKey(&'static str),

    /// At `get::<T>()`, `T` is not registered
    #[error("config `{0}` is not registered")]
    NotRegistered(&'static str),

    /// Business verification configuration failed
    #[error("invalid config `{key}`: {msg}")]
    Validation { key: &'static str, msg: String },
}

impl ConfigError {
    /// For `#[asset_config::config(validate=...)]` to generate code
    pub fn validate(key: &'static str, error: impl std::fmt::Display) -> Self {
        Self::Validation {
            key,
            msg: error.to_string(),
        }
    }
}
