#[derive(Debug, thiserror::Error)]
pub enum ConfigError {
    /// An error generated by the `config crate` itself.
    #[error(transparent)]
    Backend(#[from] config::ConfigError),

    /// Two different configurations used the same key
    #[error("config key `{0}` is already registered")]
    DuplicateKey(&'static str),

    /// Repeated registration of the same configuration type
    #[error("config type `{0}` is already registered")]
    AlreadyRegistered(&'static str),

    /// At `get::<T>()`, `T` is not registered
    #[error("config `{0}` is not registered")]
    NotRegistered(&'static str),

    /// Business verification configuration failed
    #[error("invalid config `{key}`: {msg}")]
    Validation { key: &'static str, msg: String },
}

impl ConfigError {
    /// For `#[asset_config::config(validate=...)]` to generate code
    pub fn validate(key: &'static str, error: impl std::fmt::Display) -> Self {
        Self::Validation {
            key,
            msg: error.to_string(),
        }
    }
}
