[package]
name = "asset-cli-test"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
asset-config.workspace = true
serde.workspace = true
asset-vfs.workspace = true
asset-infra = { package = "infra", path = "../infra" }
clap.workspace = true
comfy-table = { version = "8.0", default-features = false }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
tempfile = "3.27.0"
