//! Generated language-neutral contract artifacts.

use crate::{abi, manifest, protocol};
use schemars::{JsonSchema, Schema, schema_for};
use serde::Serialize;

#[derive(Debug, Serialize)]
pub struct ContractCatalog {
    pub manifest_version: u32,
    pub plugin_api: &'static str,
    pub frame: FrameCatalog,
    pub capabilities: CapabilityCatalog,
    pub views: &'static [&'static str],
    pub resource_effects: &'static [&'static str],
    pub directory_effects: &'static [&'static str],
    pub host_functions: &'static [abi::HostFunctionSpec],
}

#[derive(Debug, Serialize)]
pub struct FrameCatalog {
    pub resource_channel: &'static str,
    pub directory_channel: &'static str,
    pub resource_methods: &'static [protocol::FrameMethodSpec],
    pub directory_methods: &'static [protocol::FrameMethodSpec],
}

#[derive(Debug, Serialize)]
pub struct CapabilityCatalog {
    pub resource_actions: &'static [&'static str],
    pub directory_actions: &'static [&'static str],
}

pub fn contract_catalog() -> ContractCatalog {
    ContractCatalog {
        manifest_version: manifest::MANIFEST_VERSION,
        plugin_api: protocol::PLUGIN_API_VERSION,
        frame: FrameCatalog {
            resource_channel: protocol::PLUGIN_RESOURCE_FRAME_CHANNEL,
            directory_channel: protocol::PLUGIN_DIRECTORY_FRAME_CHANNEL,
            resource_methods: protocol::RESOURCE_FRAME_METHODS,
            directory_methods: protocol::DIRECTORY_FRAME_METHODS,
        },
        capabilities: CapabilityCatalog {
            resource_actions: manifest::RESOURCE_ACTION_CAPABILITIES,
            directory_actions: manifest::DIRECTORY_ACTION_CAPABILITIES,
        },
        views: protocol::PLUGIN_VIEW_KINDS,
        resource_effects: protocol::PLUGIN_RESOURCE_ACTION_EFFECT_KINDS,
        directory_effects: protocol::PLUGIN_DIRECTORY_ACTION_EFFECT_KINDS,
        host_functions: abi::HOST_FUNCTIONS,
    }
}

pub fn schemas() -> Vec<(&'static str, Schema)> {
    vec![
        schema::<manifest::PluginManifestDocument>("manifest-v5.schema.json"),
        schema::<manifest::PluginManifestLock>("manifest-lock-v5.schema.json"),
        schema::<protocol::PluginResourceActionRequest>("resource-action-request-v2.schema.json"),
        schema::<protocol::PluginResourceActionResult>("resource-action-result-v2.schema.json"),
        schema::<protocol::PluginDirectoryActionRequest>("directory-action-request-v2.schema.json"),
        schema::<protocol::PluginDirectoryActionResult>("directory-action-result-v2.schema.json"),
        schema::<protocol::ResourceFrameActionOutput>("resource-frame-output-v2.schema.json"),
        schema::<protocol::DirectoryFrameActionOutput>("directory-frame-output-v2.schema.json"),
        schema::<abi::DirectoryPageRequest>("directory-page-request-v2.schema.json"),
        schema::<protocol::PluginDirectoryPage>("directory-page-v2.schema.json"),
        schema::<protocol::PluginDirectoryResourcePage>("directory-resource-page-v2.schema.json"),
    ]
}

/// TypeScript constants generated from the same catalog used by Rust and JSON artifacts.
pub fn typescript_catalog_module() -> String {
    let catalog = contract_catalog();
    format!(
        "// Generated by `cargo run -p asset-plugin-api --example export_contract`; do not edit.\n\
// biome-ignore-all format: generated contract catalog\n\
export const PLUGIN_API_VERSION = {} as const;\n\
export const RESOURCE_FRAME_CHANNEL = {} as const;\n\
export const DIRECTORY_FRAME_CHANNEL = {} as const;\n\
export const resourceActionCapabilityIds = {} as const;\n\
export const directoryActionCapabilityIds = {} as const;\n\
export const resourceFrameMethods = {} as const;\n\
export const directoryFrameMethods = {} as const;\n\
export const pluginViewKinds = {} as const;\n\
export const resourceActionEffectKinds = {} as const;\n\
export const directoryActionEffectKinds = {} as const;\n",
        json(catalog.plugin_api),
        json(catalog.frame.resource_channel),
        json(catalog.frame.directory_channel),
        json(catalog.capabilities.resource_actions),
        json(catalog.capabilities.directory_actions),
        json(
            &catalog
                .frame
                .resource_methods
                .iter()
                .map(|method| method.name)
                .collect::<Vec<_>>()
        ),
        json(
            &catalog
                .frame
                .directory_methods
                .iter()
                .map(|method| method.name)
                .collect::<Vec<_>>()
        ),
        json(catalog.views),
        json(catalog.resource_effects),
        json(catalog.directory_effects),
    )
}

fn json<T: Serialize + ?Sized>(value: &T) -> String {
    serde_json::to_string(value).expect("serialize contract catalog")
}

fn schema<T: JsonSchema>(name: &'static str) -> (&'static str, Schema) {
    let mut document = serde_json::to_value(schema_for!(T)).expect("serialize JSON Schema");
    document
        .as_object_mut()
        .expect("root JSON Schema object")
        .insert(
            "$id".to_string(),
            serde_json::Value::String(format!(
                "urn:asset-hub:plugin-contract:{}",
                name.strip_suffix(".schema.json").unwrap_or(name)
            )),
        );
    apply_wire_constraints(name, &mut document);
    (
        name,
        Schema::try_from(document).expect("construct identified JSON Schema"),
    )
}

fn apply_wire_constraints(name: &str, document: &mut serde_json::Value) {
    if matches!(
        name,
        "manifest-v5.schema.json" | "manifest-lock-v5.schema.json"
    ) {
        document["properties"]["manifest_version"]["const"] =
            serde_json::Value::from(manifest::MANIFEST_VERSION);
    }
    if name == "manifest-lock-v5.schema.json" {
        document["properties"]["integrity"]["propertyNames"] = serde_json::json!({
            "pattern": r"^(?!/)(?![A-Za-z]:/)(?!.*\\)(?!.*//)(?!.*(?:^|/)\.{1,2}(?:/|$))(?!.*/$)[^\u0000-\u001F]+$"
        });
    }
    if name == "directory-page-request-v2.schema.json" {
        document["properties"]["reference"]["minLength"] = serde_json::Value::from(1);
        document["properties"]["directory_id"]["minLength"] = serde_json::Value::from(1);
        document["properties"]["cursor"]["minLength"] = serde_json::Value::from(1);
        document["properties"]["limit"]["minimum"] = serde_json::Value::from(1);
        document["properties"]["limit"]["maximum"] =
            serde_json::Value::from(abi::DIRECTORY_PAGE_MAX_LIMIT);
    }
    constrain_plugin_api(document);
}

fn constrain_plugin_api(value: &mut serde_json::Value) {
    match value {
        serde_json::Value::Object(fields) => {
            if let Some(plugin_api) = fields.get_mut("plugin_api")
                && plugin_api.is_object()
            {
                plugin_api["const"] = serde_json::Value::from(protocol::PLUGIN_API_VERSION);
            }
            for child in fields.values_mut() {
                constrain_plugin_api(child);
            }
        }
        serde_json::Value::Array(values) => {
            for child in values {
                constrain_plugin_api(child);
            }
        }
        _ => {}
    }
}
