[package]
name = "resource-text-plugin"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
asset-rust-sdk = { path = "../../../sdk/asset-rust-sdk", features = ["extism-guest"] }

[profile.release]
lto = true
opt-level = "z"
strip = true

[workspace]
